bisq-network/bisq-assets

src/main/java/bisq/asset/coins/Nilu.java, src/main/resources/META-INF/services/bisq.asset.Asset, src/test/java/bisq/asset/coins/NiluTest.java
- Official project URL: https://nilu.tech
- Official block explorer URL: http://explorer.nilu.tech
=> List Nilu (NILU)

src/main/java/bisq/asset/coins/Aquachain.java, src/main/resources/META-INF/services/bisq.asset.Asset, src/test/java/bisq/asset/coins/AquachainTest.java
- Official project URL: https://aquachain.github.io
- Official block explorer URL: http://explorer.aquanetwork.co
=> List Aquachain (AQUA)

src/main/java/bisq/asset/coins/Nimiq.java, src/main/resources/META-INF/services/bisq.asset.Asset, src/test/java/bisq/asset/coins/NimiqTest.java
- Official project URL: https://nimiq.com/
- Official block explorer URL: https://nimiq.watch/
=> List Nimiq (NIM)

src/main/java/bisq/asset/coins/Graft.java, src/main/resources/META-INF/services/bisq.asset.Asset, src/test/java/bisq/asset/coins/GraftTest.java
- Official project URL: https://www.graft.network/
- Official block explorer URL: https://blockexplorer.graft.network/
=> List Graft (GRFT)

src/main/java/bisq/asset/tokens/PixelPropertyToken.java, src/main/resources/META-INF/services/bisq.asset.Asset, src/test/java/bisq/asset/tokens/PixelPropertyTokenTest.java
- Official project URL: https://pixelproperty.io/
- Official block explorer URL: https://etherscan.io/token/0x9bc0b36cdedadb9ae906f53bdea6debe20b81b8e
=> List PixelPropertyToken (PXL)

src/main/java/bisq/asset/coins/Triton.java, src/main/resources/META-INF/services/bisq.asset.Asset, src/test/java/bisq/asset/coins/TritonTest.java
- Official project URL: https://tritonproject.org/
- Official block explorer URL: http://explorer.tritonproject.org/
Information: CryptoCurrency based on Cryptonote.
Sorry about the mess up. I am way too tired. I am pretty sure this is how you want it.
=> List Triton [TRIT]

src/main/java/bisq/asset/coins/MicroCoin.java, src/main/resources/META-INF/services/bisq.asset.Asset, src/test/java/bisq/asset/coins/MicroCoinTest.java
- Official project URL: https://microcoin.hu
- Official block explorer URL: https://explorer.microcoin.hu
=> List MicroCoin (MCC)

src/main/java/bisq/asset/coins/DACash.java, src/main/resources/META-INF/services/bisq.asset.Asset, src/test/java/bisq/asset/coins/DACashTest.java
- Official project URL: http://dacash.org/
- Official block explorer URL: http://explorer.dacash.org/
=> List DACash (DAC)

src/main/java/bisq/asset/coins/DRIP.java, src/main/resources/META-INF/services/bisq.asset.Asset, src/test/java/bisq/asset/coins/DRIPTest.java
Official project URL: https://www.dripcoin.tech/
Official block explorer URL: http://explorer.dripcoin.tech/
=> List DRIP (DRIP)

src/main/java/bisq/asset/coins/FuturoCoin.java, src/main/resources/META-INF/services/bisq.asset.Asset, src/test/java/bisq/asset/coins/FuturoCoinTest.java
- Official project URL: https://futurocoin.com/
- Official block explorer URL: https://explorer.futurocoin.com/insight/
=> List FuturoCoin (FTO)

src/main/java/bisq/asset/coins/Credits.java, src/main/resources/META-INF/services/bisq.asset.Asset, src/test/java/bisq/asset/coins/CreditsTest.java
Official project URL: https://crds.co/
Official block explorer URL: http://explorer.crds.co/
=> List Credits (CRDS)

src/main/java/bisq/asset/coins/NewPowerCoin.java, src/main/resources/META-INF/services/bisq.asset.Asset, src/test/java/bisq/asset/coins/NewPowerCoinTest.java
- Official project URL: http://npw.live
- Official block explorer URL: http://explorer.npw.live:8080
=> List NewPowerCoin (NPW)

src/main/java/bisq/asset/tokens/Pix.java, src/main/resources/META-INF/services/bisq.asset.Asset, src/test/java/bisq/asset/tokens/PixTest.java
- Official project URL: https://lampix.com/
- Official block explorer URL: https://etherscan.io/token/0x8eFFd494eB698cc399AF6231fCcd39E08fd20B15
=> List Pix (PIX)

src/main/java/bisq/asset/coins/BitcoinInstant.java, src/main/resources/META-INF/services/bisq.asset.Asset, src/test/java/bisq/asset/coins/BitcoinInstantTest.java
- Official project URL: [http://bitcoinstant.org]
- Official block explorer URL: [http://abe.getbitcoininstant.org:2750/chain/Instant]
=> List Bitcoin Instant (BTI)

src/main/java/bisq/asset/tokens/LikeCoin.java, src/main/resources/META-INF/services/bisq.asset.Asset, src/test/java/bisq/asset/tokens/LikeCoinTest.java
Official project URL: https://like.co
Official block explorer URL: https://etherscan.io/token/0x02F61Fd266DA6E8B102D4121f5CE7b992640CF98
=> List LikeCoin (LIKE)

src/main/java/bisq/asset/coins/Diamond.java, src/main/resources/META-INF/services/bisq.asset.Asset, src/test/java/bisq/asset/coins/DiamondTest.java
- Official project URL: https://bit.diamonds
- Official block explorer URL: https://chainz.cryptoid.info/dmd
=> List Diamond (DMD)

src/main/java/bisq/asset/coins/MegaCoin.java, src/main/resources/META-INF/services/bisq.asset.Asset, src/test/java/bisq/asset/coins/MegaCoinTest.java
- Official project URL: https://www.megacoin.eu
- Official block explorer URL: https://chainz.cryptoid.info/mec
=> List MegaCoin (MEC)

src/main/java/bisq/asset/coins/PRiVCY.java, src/main/resources/META-INF/services/bisq.asset.Asset, src/test/java/bisq/asset/coins/PRiVCYTest.java
* Official project URL: http://privcy.io
*  Official block explorer URL: http://explorer.privcy.io/
=> List PRiVCY (PRiV)

src/main/java/bisq/asset/coins/Motion.java, src/main/resources/META-INF/services/bisq.asset.Asset, src/test/java/bisq/asset/coins/MotionTest.java
- Official project URL: https://motionproject.org/
- Official block explorer URL: https://explorer.motionproject.org/
=> List Motion (XMN)

src/main/java/bisq/asset/coins/Credits.java
=> Change ticker to CRDS

src/main/java/bisq/asset/coins/Myriadcoin.java, src/main/resources/META-INF/services/bisq.asset.Asset, src/test/java/bisq/asset/coins/MyriadcoinTest.java
- Official project URL: https://www.myriadcoin.org/
- Official block explorer URL: https://chainz.cryptoid.info/xmy/
=> List Myriadcoin (XMY)
